config/routes.rb
Nos::Application.routes.draw do

  devise_for :users
  root "static_pages#home"

  get 'static_pages/index'

  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  resources :project_summary_forms do
    member do 
      put :toggle_approve
      get :full_summary
      get :pdf
      get :send_checklist
      get :send_checklist_facilities
      get :send_checklist_comm
      get :send_checklist_worship
      get :send_checklist_finance
      get :send_checklist_hospitality
      get :send_checklist_decorations
    end
  end

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
		  @psf_items = current_user.feed(current_user.id) if signed_in? # change this later when doing personalized feeds
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_home_content.html.erb
	<!-- < if current_user.hierarchy <= 3 %> -->
		<div class="accordion" id="psf-accordion">
			<% if @psf_items.any? %>
				<%= render partial: 'psf_item', collection: @psf_items %>
			<% else %>
				<h5 class="center">Nothing here? You either do not have any open or previous submissions. Or you have no notifications.</h5>
			<% end %>
		</div>
	<!-- < else %> -->
		<!-- <h5 class="center">Nothing here? You either do not have any open or previous submissions. Or you have no notifications.</h5> -->
	<!-- < end %> -->

app/views/static_pages/_psf_item.html.erb
<div class="accordion-group">
	<div class="accordion-heading">
		<a id="item_<%= id_convert(psf_item.title) %>_<%=psf_item.id %>" class="accordion-toggle <%= psf_item.approved? ? 'un-approved-item' : 'approved-item' %>" data-toggle="collapse" data-parent="#psf-accordion" href="#collapseItem_<%= id_convert(psf_item.title) %>_<%=psf_item.id %>"><i class="icon-list-alt"></i>
			<%= psf_item.title.upcase %>&nbsp;|&nbsp;<%= psf_item.project_manager == nil || "" ? get_user(psf_item).name.upcase : psf_item.project_manager.upcase %>
		</a>
	</div>
	<div id="collapseItem_<%= id_convert(psf_item.title) %>_<%=psf_item.id %>" class="accordion-body collapse">
		<div class="accordion-inner">
			<h5>Phone:&nbsp;<%= number_to_phone(get_user(psf_item).phone, area_code: true) %></h5>
			<h5>E-mail:&nbsp;<%= mail_to(get_user(psf_item).email, get_user(psf_item).email, subject: "Your PSF Form: #{psf_item.title}") %></h5>
			<h5>Budget:&nbsp;<%= number_to_currency(psf_item.budget) %></h5>
			<h5>Date:&nbsp;<%= psf_item.start_date %></h5>
			<h5>Location:&nbsp;<%= psf_item.location.titlecase %></h5>

			<div class="row-fluid psf-controls">
				<div class="span4">
					<% if current_user.hierarchy <= 2 %>
						<% if psf_item.approved? %>
						<%= link_to approve_link_text(psf_item), toggle_approve_project_summary_form_path(psf_item), remote: true, id:"approve_link_#{psf_item.id}", class:"btn btn-danger btn-block", method: :put %>
						<% else %>
						<%= link_to approve_link_text(psf_item), toggle_approve_project_summary_form_path(psf_item), remote: true, id:"approve_link_#{psf_item.id}", class:"btn btn-success btn-block", method: :put %>
						<% end %>
					<% end %>
				</div>
				<div class="span4">
					<% if current_user.id == psf_item.user.id %>
					<%= link_to 'Discard Item', psf_item, method: :delete, class:"btn btn-warning btn-block no-bottom demo-button button yellow", data: { confirm: "Delete: #{psf_item.title}", title: psf_item.title } %>
					<% end %>
				</div>
				<div class="span4">
					<%= link_to 'View Checklist', psf_item, class:"btn btn-info btn-block no-bottom demo-button button yellow" %>
				</div>

			</div>
		</div>
	</div>
</div>

<hr>

app/views/static_pages/about.html.erb
<% provide(:title, 'Help') %>

<h1>Information Center <br>
<small>Here are answers to frequently asked questions.</small></h1><br>

<div class="accordion" id="info-accordion">
	<div class="accordion-group">
		<div class="accordion-heading">
			<a href="#collapseOne" class="accordion-toggle" data-toggle="collapse" data-parent="#info-accordion"><h4 class="text-error text-danger">What is NOSSYM?</h4></a>
		</div>
		<div id="collapseOne" class="accordion-body collapse">
			<div class="accordion-inner">
				<p class="text-info">
					NOSSYM stands for NCCF's Online System - simple, right?<br>
					Its purpose is to provide online access to traditionally handwritten or printed forms. Any form submitted through this system has a digital trail, and is brought to the attention of the necessary person.
				</p>
			</div>
		</div>
	</div>
	<div class="accordion-group">
		<div class="accordion-heading">
			<a href="#collapseTwo" class="accordion-toggle" data-toggle="collapse" data-parent="#info-accordion"><h4 class="text-error text-danger">How do I fill out a form?</h4></a>
		</div>
		<div id="collapseTwo" class="accordion-body collapse">
			<div class="accordion-inner">
				<p class="text-info">
					Filling out forms is simple and quick! To find the form you need, simply use the navigation bar at the top of each page, select the form you need, and fill in the information. It is that easy!
				</p>
			</div>
		</div>
	</div>
	<div class="accordion-group">
		<div class="accordion-heading">
			<a href="#collapseThree" class="accordion-toggle" data-toggle="collapse" data-parent="#info-accordion"><h4 class="text-error text-danger">Who sees the information I submit?</h4></a>
		</div>
		<div id="collapseThree" class="accordion-body collapse">
			<div class="accordion-inner">
				<p class="text-info">
					Only necessary staff who are required to view the information, and subsequent conversation, are able to view your submissions. Of course, if others outside the obvious staff member(s) require information to bring a resolution to your submission, they will be granted the necessary information. <br>
					<strong>e.g. Volunteer staff setting up a requested venue who need to know how many tables &amp; chairs to set out.</strong>
				</p>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Get In Touch With Us <br>
<small>If you have questions about this system or its use, fill in the comment card below for an answer to your inquiry.</small></h1><br>

<div class="panel">
	<div class="panel-heading">
		<h4 class="panel-title">Comment Card</h4>
	</div>
	<form class="">
		<fieldset>
			<legend></legend>
			<div class="form-group">
				<label for="exampleInputEmail">Email address</label>
				<input type="text" class="form-control" id="email" placeholder="Enter email">
			</div>
			<div class="comment">
				<textarea class="form-control" rows="3"></textarea>
			</div>
			<button type="submit" class="btn btn-default">Submit</button>
		</fieldset>
	</form>
</div>

<br>
<h4>Or if you prefer to be a bit more personal!</h4>
<h5 class="text-warning">Send us a letter</h5>
<address>
	<strong>New Creation Christian Fellowship</strong><br>
	8700 Four Winds Dr<br>
	Windcrest, Tx 78239<br>
	<abbr title="Phone">P:</abbr>&nbsp;(210) 646-7997
</address>
<h5 class="text-warning">Send us an e-mail</h5>
<address>
	<strong>Ans R. Giver</strong><br>
	<a href="mailto:#">ansr.giver@nccf-sa.org</a>
</address>

<address>
  <strong>Twitter, Inc.</strong><br>
  795 Folsom Ave, Suite 600<br>
  San Francisco, CA 94107<br>
  <abbr title="Phone">P:</abbr> (123) 456-7890
</address>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Information Center <br>
<small>Here are answers to frequently asked questions.</small></h1><br>

<div class="accordion" id="info-accordion">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a href="#collapseOne" class="accordion-toggle" data-toggle="collapse" data-parent="#info-accordion"><h4 class="text-error text-danger">What is NOSSYM?</h4></a>
    </div>
    <div id="collapseOne" class="accordion-body collapse">
      <div class="accordion-inner">
        <p class="text-info">
          NOSSYM stands for NCCF's Online System - simple, right?<br>
          Its purpose is to provide online access to traditionally handwritten or printed forms. Any form submitted through this system has a digital trail, and is brought to the attention of the necessary person.
        </p>
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a href="#collapseTwo" class="accordion-toggle" data-toggle="collapse" data-parent="#info-accordion"><h4 class="text-error text-danger">How do I fill out a form?</h4></a>
    </div>
    <div id="collapseTwo" class="accordion-body collapse">
      <div class="accordion-inner">
        <p class="text-info">
          Filling out forms is simple and quick! To find the form you need, simply use the navigation bar at the top of each page, select the form you need, and fill in the information. It is that easy!
        </p>
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a href="#collapseThree" class="accordion-toggle" data-toggle="collapse" data-parent="#info-accordion"><h4 class="text-error text-danger">Who sees the information I submit?</h4></a>
    </div>
    <div id="collapseThree" class="accordion-body collapse">
      <div class="accordion-inner">
        <p class="text-info">
          Only necessary staff who are required to view the information, and subsequent conversation, are able to view your submissions. Of course, if others outside the obvious staff member(s) require information to bring a resolution to your submission, they will be granted the necessary information. <br>
          <strong>e.g. Volunteer staff setting up a requested venue who need to know how many tables &amp; chairs to set out.</strong>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
	<%= render 'home_content' %>
<% else %>
	<div class="center hero-unit">
		<h1>NOS Management System</h1>

		<p>The online management system for New Creation Christian Fellowship!</p>

		<%= link_to "Sign in now!", new_user_session_path, class: "btn btn-large btn-primary" %>
	</div> <br>

	<hr>

	<div class="row-fluid">
		<div class="span3 offset1">
			<h2>Get in touch with us quickly!</h2>
			<p>We've brought our paper forms online for faster submission and easier management! </p>
		</div><!--/span-->
		<div class="span3">
			<h2>Very optimized!</h2>
			<p>The online service is engineered to help productivity. As such, it has been designed with mobile usage in mind! </p>
		</div><!--/span-->
		<div class="span3">
			<h2>Documented for everyone!</h2>
			<p>We are making sure you will have help using the system by keeping helpful guides covering basic functionality! </p>
		</div><!--/span-->
	</div><!--/row-->
<% end %>