config/routes.rb
Nos::Application.routes.draw do

  devise_for :users
  root "static_pages#home"

  get 'static_pages/index'

  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  resources :project_summary_forms do
    member do 
      put :toggle_approve
      get :full_summary
      get :pdf
      get :send_checklist
      get :send_checklist_facilities
      get :send_checklist_comm
      get :send_checklist_worship
      get :send_checklist_finance
      get :send_checklist_hospitality
      get :send_checklist_decorations
    end
  end

  

end

app/views/layouts/bootstrap/OLD-_footer.html.erb
<footer class="footer">
	<small>
		<a href="<%= root_url %>">NOSSYM</a>
		by Jacob Pagano&nbsp;|&nbsp;
		&copy; New Creation Christian Fellowship 2013
	</small>
	<nav>
		<ul>
			<li><%= link_to "About",   about_path %></li>
			<li><%= link_to "Contact",	contact_path %></li>
			<li><a href="https://github.com/Jacobichou">Developer</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/bootstrap/OLD-_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container-fluid">
			<!-- <button id="showLeft" type="button" class="btn btn-navbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button> -->
			<!-- <= link_to "NOSSYM", root_path, class: "brand" %> -->
			<% if user_signed_in? %>
				<button id="showLeft" type="button" class="brand btn-inverse">Menu</button>
			<% else %>
				<%= link_to 'Sign In', new_user_session_path, class: "brand btn-primary" %>
				<!-- <button id="showRight" type="button" class="brand btn-primary">Sign In</button> -->
			<% end %>

			<div class="nav-collapse collapse">
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>

<%= render 'layouts/menu' %>

app/views/layouts/bootstrap/OLD-application.html.erb
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
	<meta charset="utf-8">
	<title><%= full_title(yield(:title)) %></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
	<meta name="HandheldFriendly" content="true" />
	<meta name="description" content="">
	<meta name="author" content="">
	<%= render 'layouts/fav_touch' %>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body class="cbp-spmenu-push">

	<%= render 'layouts/header' %>
	
	<div class="container center">
		<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>
	</div>

	<div class="container-fluid">
		<div class="row-fluid">


			<div class="span12">
				<div class="container">
					<%= yield %>
				</div>
				
			</div><!--/span-->
		</div><!--/row-->

		<hr>

		<%= render 'layouts/footer' %>

	</div><!--/.fluid-container-->
	<!-- <= javascript_include_tag "classie" %>
	<= javascript_include_tag "menu" %> -->
	<%= render 'layouts/menu_js' %>
</body>
</html>

app/views/layouts/bootstrap/_menu.html.erb
<nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
	<% if user_signed_in? %>
		<h4>Welcome, <%= current_user.name %></h4>
	<% else %>
		<h4>NOSSYM</h4>
	<% end %>
		<%= link_to "Home", home_path %>
		<%= link_to "Help", help_path %>
		<%= link_to "Contact Us", contact_path %>
	<br>
	<h5><strong>Forms</strong></h5>
	<%= link_to 'PSF', new_project_summary_form_path %>
	<br>
	<% if user_signed_in? %>
		<h5><strong>Settings</strong></h5>
		<a href="#">Profile</a>
		<%= link_to "Sign out", destroy_user_session_path, method: "delete", class: "btn-danger text-center" %>
	<% end %>
</nav>

<nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right" id="cbp-spmenu-s2">
	<h3>Sign In</h3>
	<a href="#"></a>
</nav>

app/views/layouts/bootstrap/_menu_js.html.erb
<script type="text/javascript">

/*!
 * classie - class helper functions
 * from bonzo https://github.com/ded/bonzo
 * 
 * classie.has( elem, 'my-class' ) -> true/false
 * classie.add( elem, 'my-new-class' )
 * classie.remove( elem, 'my-unwanted-class' )
 * classie.toggle( elem, 'my-class' )
 */

/*jshint browser: true, strict: true, undef: true */

( function( window ) {

'use strict';

// class helper functions from bonzo https://github.com/ded/bonzo

function classReg( className ) {
  return new RegExp("(^|\\s+)" + className + "(\\s+|$)");
}

// classList support for class management
// altho to be fair, the api sucks because it won't accept multiple classes at once
var hasClass, addClass, removeClass;

if ( 'classList' in document.documentElement ) {
  hasClass = function( elem, c ) {
    return elem.classList.contains( c );
  };
  addClass = function( elem, c ) {
    elem.classList.add( c );
  };
  removeClass = function( elem, c ) {
    elem.classList.remove( c );
  };
}
else {
  hasClass = function( elem, c ) {
    return classReg( c ).test( elem.className );
  };
  addClass = function( elem, c ) {
    if ( !hasClass( elem, c ) ) {
      elem.className = elem.className + ' ' + c;
    }
  };
  removeClass = function( elem, c ) {
    elem.className = elem.className.replace( classReg( c ), ' ' );
  };
}

function toggleClass( elem, c ) {
  var fn = hasClass( elem, c ) ? removeClass : addClass;
  fn( elem, c );
}

window.classie = {
  // full names
  hasClass: hasClass,
  addClass: addClass,
  removeClass: removeClass,
  toggleClass: toggleClass,
  // short names
  has: hasClass,
  add: addClass,
  remove: removeClass,
  toggle: toggleClass
};

})( window );
	
var menuLeft = document.getElementById( 'cbp-spmenu-s1' ),
				menuRight = document.getElementById( 'cbp-spmenu-s2' ),
				menuTop = document.getElementById( 'cbp-spmenu-s3' ),
				menuBottom = document.getElementById( 'cbp-spmenu-s4' ),
				showLeft = document.getElementById( 'showLeft' ),
				showRight = document.getElementById( 'showRight' ),
				showTop = document.getElementById( 'showTop' ),
				showBottom = document.getElementById( 'showBottom' ),
				showLeftPush = document.getElementById( 'showLeftPush' ),
				showRightPush = document.getElementById( 'showRightPush' ),
				body = document.body;

			showLeft.onclick = function() {
				classie.toggle( this, 'active' );
				classie.toggle( menuLeft, 'cbp-spmenu-open' );
				disableOther( 'showLeft' );
			};
			showRight.onclick = function() {
				classie.toggle( this, 'active' );
				classie.toggle( menuRight, 'cbp-spmenu-open' );
				disableOther( 'showRight' );
			};
			showTop.onclick = function() {
				classie.toggle( this, 'active' );
				classie.toggle( menuTop, 'cbp-spmenu-open' );
				disableOther( 'showTop' );
			};
			showBottom.onclick = function() {
				classie.toggle( this, 'active' );
				classie.toggle( menuBottom, 'cbp-spmenu-open' );
				disableOther( 'showBottom' );
			};
			showLeftPush.onclick = function() {
				classie.toggle( this, 'active' );
				classie.toggle( body, 'cbp-spmenu-push-toright' );
				classie.toggle( menuLeft, 'cbp-spmenu-open' );
				disableOther( 'showLeftPush' );
			};
			showRightPush.onclick = function() {
				classie.toggle( this, 'active' );
				classie.toggle( body, 'cbp-spmenu-push-toleft' );
				classie.toggle( menuRight, 'cbp-spmenu-open' );
				disableOther( 'showRightPush' );
			};

			function disableOther( button ) {
				if( button !== 'showLeft' ) {
					classie.toggle( showLeft, 'disabled' );
				}
				if( button !== 'showRight' ) {
					classie.toggle( showRight, 'disabled' );
				}
				if( button !== 'showTop' ) {
					classie.toggle( showTop, 'disabled' );
				}
				if( button !== 'showBottom' ) {
					classie.toggle( showBottom, 'disabled' );
				}
				if( button !== 'showLeftPush' ) {
					classie.toggle( showLeftPush, 'disabled' );
				}
				if( button !== 'showRightPush' ) {
					classie.toggle( showRightPush, 'disabled' );
				}
			}
	</script>

app/views/layouts/bootstrap/_shim.html.erb
<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
	<script src="../assets/js/html5shiv.js"></script>
<![endif]-->