config/routes.rb
Nos::Application.routes.draw do

  devise_for :users
  root "static_pages#home"

  get 'static_pages/index'

  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  resources :project_summary_forms do
    member do 
      put :toggle_approve
      get :full_summary
      get :pdf
      get :send_checklist
      get :send_checklist_facilities
      get :send_checklist_comm
      get :send_checklist_worship
      get :send_checklist_finance
      get :send_checklist_hospitality
      get :send_checklist_decorations
    end
  end

  

end

app/controllers/project_summary_forms_controller.rb
class ProjectSummaryFormsController < ApplicationController
	before_filter :authenticate_user!
	before_action :set_project_summary_form, only: [:show, :edit, :update, :destroy]
	PSF_HIER_LVL = 3 # dictates that anyone of 0, 1, 2, 3(superAdmin, admin, supervisor, employee, member) hierarchy levels can view or receive something

	def create
		@project_summary_form = current_user.project_summary_forms.create(psf_params)

		respond_to do |format|
			if @project_summary_form.save
				UserMailer.email_notify(PSF_HIER_LVL, @project_summary_form, "psf").deliver
				format.html { redirect_to @project_summary_form, notice: 'Project summary form was successfully created.' }
				format.json { render action: 'show', status: :created, location: @project_summary_form }
			else
				format.html { render action: 'new' }
				format.json { render json: @project_summary_form.errors, status: :unprocessable_entity }
			end
		end
	end

	def new
		@project_summary_form = ProjectSummaryForm.new

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @psf }
		end
	end

	def show
	end

	def edit
	end

	def pdf
		# @project_summary_form = ProjectSummaryForm.find_by_id(params[:id])

		respond_to do |format|
			format.html
			format.pdf do
		      render :pdf => "my_pdf", # pdf will download as my_pdf.pdf
		        :layout => 'pdf', # uses views/layouts/pdf.haml
		    :show_as_html => params[:debug].present? # renders html version if you set debug=true in URL
		 end
		end

	end

	def full_summary
		@project_summary_form = ProjectSummaryForm.find_by_id(params[:id])
	end

	def update
		respond_to do |format|
			if @project_summary_form.update(psf_params)
				UserMailer.email_notify(PSF_HIER_LVL, @project_summary_form, "psf-update").deliver
				format.html { redirect_to @project_summary_form, notice: 'Project summary form was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @project_summary_form.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@project_summary_form.destroy
		respond_to do |format|
			format.html { redirect_to home_path }
			format.json { head :no_content }
		end
		UserMailer.notify_discarded(@project_summary_form).deliver if @project_summary_form.destroyed?
	end

	def toggle_approve
		@project_summary_form = ProjectSummaryForm.find(params[:id])
		@project_summary_form.toggle!(:approved)
		respond_to do |format|
			format.html { redirect_to :back, notice: "Changed" }
			format.js
		end
		unless @project_summary_form.approved?
			UserMailer.notify_unapproved(@project_summary_form).deliver
		else
			UserMailer.notify_approved(@project_summary_form).deliver
		end
	end

	def send_checklist
		@project_summary_form = ProjectSummaryForm.find(params[:id])
		respond_to do |format|
			format.html { redirect_to :back, notice: "Details sent" }
			format.js
		end
		UserMailer.send_checklist(@project_summary_form, "jacobis.person@gmail.com").deliver
	end

	def send_checklist_facilities
		@project_summary_form = ProjectSummaryForm.find(params[:id])
		respond_to do |format|
			format.html { redirect_to :back, notice: "Details sent" }
			format.js
		end
		UserMailer.send_checklist_facilities(@project_summary_form, "dmarbury@nccf-sa.org").deliver
	end

	def send_checklist_comm
		@project_summary_form = ProjectSummaryForm.find(params[:id])
		respond_to do |format|
			format.html { redirect_to :back, notice: "Details sent" }
			format.js
		end
		UserMailer.send_checklist_comm(@project_summary_form, "bishopjeh@nccf-sa.org").deliver
	end

	def send_checklist_worship
		@project_summary_form = ProjectSummaryForm.find(params[:id])
		respond_to do |format|
			format.html { redirect_to :back, notice: "Details sent" }
			format.js
		end
		UserMailer.send_checklist_worship(@project_summary_form, "renetha@nccf-sa.org").deliver
	end

	def send_checklist_finance
		@project_summary_form = ProjectSummaryForm.find(params[:id])
		respond_to do |format|
			format.html { redirect_to :back, notice: "Details sent" }
			format.js
		end
		UserMailer.send_checklist_finance(@project_summary_form, "laura@nccf-sa.org").deliver
	end

	def send_checklist_hospitality # sends menu, greeters and ushers info bcz it goes to same person
		@project_summary_form = ProjectSummaryForm.find(params[:id])
		respond_to do |format|
			format.html { redirect_to :back, notice: "Details sent" }
			format.js
		end
		UserMailer.send_checklist_hospitality(@project_summary_form, "sross@nccf-sa.org").deliver
	end

	def send_checklist_decorations
		@project_summary_form = ProjectSummaryForm.find(params[:id])
		respond_to do |format|
			format.html { redirect_to :back, notice: "Details sent" }
			format.js
		end
		UserMailer.send_checklist_decorations(@project_summary_form, "sross@nccf-sa.org").deliver
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_project_summary_form
			@project_summary_form = ProjectSummaryForm.find(params[:id])
		end

		def psf_params
			params.require(:project_summary_form).permit(:project_manager, :location, :budget, :revenue, 
				:title, :purpose, :frequency, :frequency_exception, :fee, :offering, 
				:comments, :start_date, :end_date, :start_time, :end_time, 
				:num_participants, :request_type, :audience, :outcome, :additional_requests, 
				:objectives, :facilities, :comm, :worship_council, :day_staff, :menu, 
				:greeters, :ushers, :ministry_leader, :marketing, :decorations)
		end

		def full_summary_params
			params.fetch(:full_summary, {}).permit(:additional_requests, :objectives, :facilities, :comm, :worship_council, :day_staff, :menu, 
				:greeters, :ushers, :ministry_leader, :marketing, :decorations)
		end

		def can_view?
			if current_user.hierarchy >=3
				return true
			else
				return false
			end
		end
	end

app/helpers/project_summary_forms_helper.rb
module ProjectSummaryFormsHelper

	def li_prepare(item)
		@item = item.insert(0,",").gsub!(/,\s*/, '<li>').html_safe unless item.nil?
	end

end

app/views/project_summary_forms/_full_summary_form.html.erb
<%= form_for(@project_summary_form) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<fieldset>

  <div class="row-fluid">
    <div class="span12">
      <h4>Additional requests for Pastor Copeland:</h4>

      <!-- <= f.label :purpose, "Purpose of event:", class:"span12" %> -->
      <!-- <= f.text_field :additional_requests, placeholder: "e.g. A token of her appreciation", class:"span12" %> -->

      <div class="input-prepend">
        <span class="add-on">Requests:</span>
        <%= f.text_field :additional_requests, placeholder: "e.g. A token of her appreciation", class:"span12" %>
      </div>

    </div>
  </div>

  <hr>
<h4 class="muted">Separate items with a comma(,)</h4> <br>
  <div class="row-fluid">
    <div class="span12">
      <!-- <= f.label :purpose, "Purpose of event:", class:"span12" %> -->
      <%= f.text_field :facilities, placeholder: "Factilities", class:"span12" %>

      <!-- <= f.label :audience, "Target audience:", class:"span12" %> -->
      <%= f.text_field :comm, placeholder: "Production & Audio/Visual", class:"span12" %>

      <!-- <= f.label :outcome, "Expected outcome:", class:"span12" %> -->
      <%= f.text_field :worship_council, placeholder: "Worship Council", class:"span12" %>

      <!-- <= f.label :outcome, "Expected outcome:", class:"span12" %> -->
      <%= f.text_field :day_staff, placeholder: "Day staff", class:"span12" %>

      <!-- <= f.label :outcome, "Expected outcome:", class:"span12" %> -->
      <%= f.text_field :menu, placeholder: "The menu", class:"span12" %>

      <!-- <= f.label :outcome, "Expected outcome:", class:"span12" %> -->
      <%= f.text_field :greeters, placeholder: "Greeters", class:"span12" %>

      <!-- <= f.label :outcome, "Expected outcome:", class:"span12" %> -->
      <%= f.text_field :ushers, placeholder: "Ushers", class:"span12" %>

      <!-- <= f.label :outcome, "Expected outcome:", class:"span12" %> -->
      <%= f.text_field :ministry_leader, placeholder: "Ministry Leader", class:"span12" %>

      <!-- <= f.label :outcome, "Expected outcome:", class:"span12" %> -->
      <%= f.text_field :marketing, placeholder: "Marketing", class:"span12" %>

      <!-- <= f.label :outcome, "Expected outcome:", class:"span12" %> -->
      <%= f.text_field :decorations, placeholder: "Decorations", class:"span12" %>
    </div>
  </div>

  <hr>

  <div class="actions center">
    <%= f.submit 'Submit', class:"btn btn-large btn-primary btn-block", data: {disable_with: "Submitting..."} %>
  </div>
</fieldset>

<% end %>

app/views/project_summary_forms/_psf_form.html.erb
<%= form_for(@project_summary_form) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<fieldset>
  <div class="row-fluid">
    <div class="span12">
      <label class="radio inline">
        <%= f.radio_button :request_type, "Van Request" %>
        Van Request
      </label>
      <label class="radio inline">
        <%= f.radio_button :request_type, "Facility or Meeting Request" %>
        Facility/Meeting Request
      </label>
      <label class="radio inline">
        <%= f.radio_button :request_type, "Event or Project" %>
        Event/Project
      </label>
    </div>
  </div>

  <hr>

  <div class="row-fluid">
    <div class="span12">
      <!-- <= f.label :title, "Event Title:", class:"span12" %> -->
      <%= f.text_field :title, placeholder: "Event Title", class:"span12" %>

      <!-- <= f.label :location, "Location:", class:"span12" %> -->
      <%= f.text_field :location, placeholder: "Location", class:"span12" %>
    </div>
  </div>
  <!-- add ajax person finder box -->

  <hr>

  <div class="row-fluid">
    <div class="span6">
      <%= f.label :start_time, "Start time", class:"span12" %>
      <%= f.time_field :start_time %>
    </div>

    <div class="span6">
      <%= f.label :end_time, "End time", class:"span12" %>
      <%= f.time_field :end_time %>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span6">
      <%= f.label :start_date, "Start date", class:"span12" %>
      <%= f.date_field :start_date %>
    </div>

    <div class="span6">
      <%= f.label :end_date, "End date", class:"span12" %>
      <%= f.date_field :end_date %>
    </div>
  </div>

  <hr>

  <div class="row-fluid">
    <div class="span12">
      <!-- <= f.label :frequency, "Indicate if recurring event by giving the frequency (e.g. Each Sunday after 8pm):", class:"span12" %> -->
      <%= f.text_field :frequency, placeholder: "Indicate if recurring event by giving the frequency (e.g. Each Sunday after 8pm)", class:"span12" %>

      <!-- <= f.label :frequency_exception, "Indicate exception for recurring event (e.g. the date during Thanksgiving week):", class:"span12" %> -->
      <%= f.text_field :frequency_exception, placeholder: "Indicate exception for recurring event (e.g. the date during Thanksgiving week)", class:"span12" %>
    </div>
  </div>

  <hr>

  <div class="row-fluid">
    <div class="span12">
      <!-- <= f.label :purpose, "Purpose of event:", class:"span12" %> -->
      <%= f.text_area :purpose, placeholder: "Purpose of event", class:"span12" %>

      <!-- <= f.label :audience, "Target audience:", class:"span12" %> -->
      <%= f.text_field :audience, placeholder: "Target audience", class:"span12" %>

      <!-- <= f.label :outcome, "Expected outcome:", class:"span12" %> -->
      <%= f.text_field :outcome, placeholder: "Expected outcome", class:"span12" %>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <!-- <= f.label :purpose, "Purpose of event:", class:"span12" %> -->
      <%= f.text_field :num_participants, placeholder: "Number of participants (e.g. 'unlimited', or '5')", class:"span12" %>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <div class="input-prepend input-append">
        <span class="add-on">$</span>
        <%= f.number_field :budget, placeholder: "Budget (nearest dollar)", class:"span12" %>
        <span class="add-on">.00</span>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <div class="input-prepend input-append">
        <span class="add-on">$</span>
        <%= f.number_field :revenue, placeholder: "Estimated revenue (nearest dollar)", class:"span12" %>
        <span class="add-on">.00</span>
      </div>
    </div>
  </div>

  <hr>

  <div class="row-fluid">
    <div class="span12">
      <div class="input-prepend input-append">
        <span class="add-on">$</span>
        <%= f.number_field :fee, placeholder: "Event fee", class:"span12" %>
        <span class="add-on">.00</span>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      Will there be an offering? <br>
      <label class="radio inline">
        <%= f.radio_button :offering, "true" %>
        Yes
      </label>
      <label class="radio inline">
        <%= f.radio_button :offering, "false" %>
        No
      </label>
    </div>
  </div>

  <hr>

  <div class="actions center">
    <%= f.submit 'Submit', class:"btn btn-large btn-primary btn-block", data: {disable_with: "Submitting..."} %>
  </div>
</fieldset>
<% end %>

app/views/project_summary_forms/edit.html.erb
<div class="container">
	<h1>Editing</h1>
	<h3><%= @project_summary_form.title.titlecase %></h3>
</div>

<%= render 'psf_form' %>

<hr>
<%= link_to 'Show', @project_summary_form, class: "btn btn-info btn-large btn-block" %>
<%= link_to 'Back', home_path, class: "btn btn-large btn-block" %>

app/views/project_summary_forms/full_summary.html.erb
<div class="container">
	<h1>Editing Full Summary</h1>
	<h3><%= @project_summary_form.title.titlecase %></h3>	
</div>

<hr>

<%= render 'full_summary_form' %>

<hr>
<%= link_to 'Show', @project_summary_form, class: "btn btn-large btn-info btn-block" %>
<%= link_to 'Back', home_path, class: "btn btn-large btn-block" %>

app/views/project_summary_forms/pdf.html.erb
<h1> Welcome!</h1>

<% if request.format.html? %>
  #sidebar
    This is a sidebar. It will only be visible in the HTML version.
    <% end %>


  The requested format is: <%= "#{request.format.to_s}" %>!


  <%= link_to "Download as PDF", url_for(request.params.merge(:format => :pdf)) if request.format.html? %>

app/views/project_summary_forms/send_checklist.js.erb
$("#send_checklist_facilities").removeClass("btn-warning").addClass("btn-success disabled").text("Sent")
// $("#send-details-facilities").html("<%= link_to 'Sent', '#', id:'send_checklist_facilities', class:'btn btn-success btn-block disabled' %>")

app/views/project_summary_forms/send_checklist_comm.js.erb
$("#send_checklist_comm").removeClass("btn-warning").addClass("btn-success disabled").text("Sent")
// $("#send-details-comm").html("<%= link_to 'Sent', '#', id:'send_checklist_facilities', class:'btn btn-success btn-block disabled' %>")

app/views/project_summary_forms/send_checklist_decorations.js.erb
$("#send_checklist_decorations").removeClass("btn-warning").addClass("btn-success disabled").text("Sent")
// $("#send-details-decorations").html("<%= link_to 'Sent', '#', id:'send_checklist_facilities', class:'btn btn-success btn-block disabled' %>")

app/views/project_summary_forms/send_checklist_facilities.js.erb
$("#send_checklist_facilities").removeClass("btn-warning").addClass("btn-success disabled").text("Sent")
// $("#send-details-facilities").html("<%= link_to 'Sent', '#', id:'send_checklist_facilities', class:'btn btn-success btn-block disabled' %>")

app/views/project_summary_forms/send_checklist_finance.js.erb
$("#send_checklist_finance").removeClass("btn-warning").addClass("btn-success disabled").text("Sent")
// $("#send-details-finance").html("<%= link_to 'Sent', '#', id:'send_checklist_facilities', class:'btn btn-success btn-block disabled' %>")

app/views/project_summary_forms/send_checklist_hospitality.js.erb
$("#send_checklist_hospitality").removeClass("btn-warning").addClass("btn-success disabled").text("Sent")
// $("#send-details-hospitality").html("<%= link_to 'Sent', '#', id:'send_checklist_facilities', class:'btn btn-success btn-block disabled' %>")

app/views/project_summary_forms/send_checklist_worship.js.erb
$("#send_checklist_worship").removeClass("btn-warning").addClass("btn-success disabled").text("Sent")
// $("#send-details-worship").html("<%= link_to 'Sent', '#', id:'send_checklist_facilities', class:'btn btn-success btn-block disabled' %>")

// interesting note: another .js.erb file was running an action on a different div than its owner div and it worked then,but not earlier? Hmm..

app/views/project_summary_forms/show.html.erb
<div class="summary-view">
  <h1>
    New Creation Christian Fellowship <br>
    <small>of San Antonio, Tx</small>
  </h1>

  <hr>
  <%= link_to 'Add Checklist Details', full_summary_project_summary_form_path, class: "btn btn-large btn-info btn-block" %>
  <hr>

  <h4>Project:&nbsp;<span class="muted"><%= @project_summary_form.title.titlecase %></span></h4>
  <h4>Prepared <em>and</em> Submitted:&nbsp;<span class="muted"><%= @project_summary_form.created_at.strftime("%B %d %Y") %></span></h4>
  <h5>Request Type:&nbsp;<span class="muted"><%= @project_summary_form.request_type %></span></h5>

  <div class="row-fluid">
    <div class="span12">
      <dl class="dl-horizontal">
        <dt>Date(s):&nbsp;</dt>
        <dd><%= @project_summary_form.start_date.nil? ? "----" : @project_summary_form.start_date.strftime("%A, %B %d %Y") %>&nbsp;<strong>thru</strong>&nbsp;<%= @project_summary_form.end_date.nil? ? "----" : @project_summary_form.end_date.strftime("%A, %B %d %Y") %>

          <dt>Time:&nbsp;</dt>
          <dd><%= @project_summary_form.start_time.nil? ? "----" : @project_summary_form.start_time.strftime("%I:%M %p") %>&nbsp;-&nbsp;<%= @project_summary_form.end_time.nil? ? "----" : @project_summary_form.end_time.strftime("%I:%M %p") %></dd>

          <dt>Frequency:&nbsp;</dt>
          <dd><%= @project_summary_form.frequency %></dd>

          <dt>Project Manager:&nbsp;</dt>
          <dd><%= @project_summary_form.user.name.titlecase %></dd>

          <dt>Phone:&nbsp;</dt>
          <dd><%= number_to_phone(@project_summary_form.user.phone) %></dd>

          <dt>Location:&nbsp;</dt>
          <dd><%= @project_summary_form.location.titlecase unless @project_summary_form.location.nil? %></dd>

          <dt>Purpose:&nbsp;</dt>
          <dd><%= @project_summary_form.purpose %></dd>

          <dt>Audience:&nbsp;</dt>
          <dd><%= @project_summary_form.audience %></dd>

          <dt>Outcome:&nbsp;</dt>
          <dd><%= @project_summary_form.outcome %></dd>

          <dt>Objectives:&nbsp;</dt>
          <dd>
            <ul>
              <%= li_prepare(@project_summary_form.objectives) %> <!-- /,\s*/ -->
            </ul>
          </dd>
        </dl>
      </div>
    </div>

    <h4>Receive from Pastor Copeland:</h4>

    <div class="row-fluid">
      <div class="span12">
        <dl class="dl-horizontal">
          <dt>Budget:&nbsp;</dt>
          <dd><%= number_to_currency(@project_summary_form.budget) %></dd>

          <dt>Income:&nbsp;</dt>
          <dd><%= number_to_currency(@project_summary_form.revenue) %></dd>
        </dl>

        <h5>Additional requests:</h5>
        <ul>
          <%= li_prepare(@project_summary_form.additional_requests) %>
        </ul>
      </div>
    </div>

    <hr>

    <h4>Requirements:</h4>

    <div class="row-fluid">
      <div class="span12">
        <dt>Facilities (Deacon Darryl Marbury):</dt>
        <dd><%= li_prepare(@project_summary_form.facilities) %></dd>
        <div id="send-details-facilities" class="send-details">
          <%= link_to "Notify Facilities", send_checklist_facilities_project_summary_form_path(@project_summary_form), remote: true, id:"send_checklist_facilities", class:"btn btn-info btn-block", data: { disable_with: "Sending..." } if current_user.hierarchy <= 2 %>
        </div>

        <hr>

        <dt>Communications (Bishop Harker):</dt>
        <dd><%= li_prepare(@project_summary_form.comm) %></dd>
        <div id="send-details-comm" class="send-details">
          <%= link_to "Notify Communications", send_checklist_comm_project_summary_form_path(@project_summary_form), remote: true, id:"send_checklist_comm", class:"btn btn-info btn-block", data: { disable_with: "Sending..." } if current_user.hierarchy <= 2 %>
        </div>

        <hr>

        <dt>Worship Council (Elder Renetha Macklin):</dt>
        <dd><%= li_prepare(@project_summary_form.worship_council) %></dd>
        <div id="send-details-worship" class="send-details">
          <%= link_to "Notify Worship Council", send_checklist_worship_project_summary_form_path(@project_summary_form), remote: true, id:"send_checklist_worship", class:"btn btn-info btn-block", data: { disable_with: "Sending..." } if current_user.hierarchy <= 2 %>
        </div>

        <hr>

        <dt>Finance (Laura Peebles):</dt>
        <dd><%= li_prepare(@project_summary_form.day_staff) %></dd>
        <div id="send-details-finance" class="send-details">
          <%= link_to "Notify Finance", send_checklist_finance_project_summary_form_path(@project_summary_form), remote: true, id:"send_checklist_finance", class:"btn btn-info btn-block", data: { disable_with: "Sending..." } if current_user.hierarchy <= 2 %>
        </div>

        <hr>

        <dt>Hospitality (Sister Sandra Ross):</dt>
        <dd><%= li_prepare(@project_summary_form.menu) %></dd>

        <dt>Greeters (Sister Sandra Ross):</dt>
        <dd><%= li_prepare(@project_summary_form.greeters) %></dd>

        <dt>Ushers (Sister Sandra Ross):</dt>
        <dd><%= li_prepare(@project_summary_form.ushers) %></dd>
        <div id="send-details-hospitality" class="send-details">
          <%= link_to "Notify Hospitality", send_checklist_hospitality_project_summary_form_path(@project_summary_form), remote: true, id:"send_checklist_hospitality", class:"btn btn-info btn-block", data: { disable_with: "Sending..." } if current_user.hierarchy <= 2 %>
        </div>

        <hr>

        <dt>Decorations (Sister Nichelle Hosley):</dt>
        <dd><%= li_prepare(@project_summary_form.decorations) %></dd>
        <div id="send-details-decorations" class="send-details">
          <%= link_to "Notify Decorator", send_checklist_decorations_project_summary_form_path(@project_summary_form), remote: true, id:"send_checklist_decorations", class:"btn btn-info btn-block", data: { disable_with: "Sending..." } if current_user.hierarchy <=2 %>
        </div>
      </div>
    </div>

    <hr>

    <div class="row-fluid">
      <div class="span12">
        <div class="accordion" id="psf-more-info">
          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                EXTRA INFORMATION...
              </a>
            </div>
            <div id="collapseOne" class="accordion-body collapse">
              <div class="accordion-inner">
                <dl class="dl-horizontal">
                  <dt>Frequency Exception:&nbsp;</dt>
                  <dd><%= @project_summary_form.frequency_exception %></dd>

                  <dt>Event Fee:&nbsp;</dt>
                  <dd><%= number_to_currency(@project_summary_form.fee) %></dd>

                  <dt>Offering Taken?:&nbsp;</dt>
                  <dd><%= @project_summary_form.offering %></dd>

                  <dt>Num of participants?:&nbsp;</dt>
                  <dd><%= @project_summary_form.num_participants %></dd>

                  <dt>Admin Comments:&nbsp;</dt>
                  <dd><%= @project_summary_form.comments %></dd>
                </dl>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <hr>
    <%= link_to 'Edit PSF Form', edit_project_summary_form_path(@project_summary_form), class: "btn btn-large btn-warning btn-block" %>
    <%= link_to 'Overview', home_path, class: "btn btn-large btn-block" %>

  </div>

app/views/project_summary_forms/toggle_approve.js.erb
$("#approve_link_<%= @project_summary_form.id %>").html("<%= approve_link_text(@project_summary_form) %>")
$("#item_<%= id_convert(@project_summary_form.title) %>_<%=@project_summary_form.id %>").html()

if ( <%= @project_summary_form.approved? %> ) {
	$("#item_<%= id_convert(@project_summary_form.title) %>_<%=@project_summary_form.id %>").removeClass("approved-item").addClass("un-approved-item")
	$("#approve_link_<%= @project_summary_form.id %>").removeClass("btn-success").addClass("btn-danger")
}
else {
	$("#item_<%= id_convert(@project_summary_form.title) %>_<%=@project_summary_form.id %>").removeClass("un-approved-item").addClass("approved-item")
	$("#approve_link_<%= @project_summary_form.id %>").removeClass("btn-danger").addClass("btn-success")
}